// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/contactFormConvex.ts";
import * as $$$$$$$$$1 from "./actions/contactFormConvexFixed.ts";
import * as $$$$$$$$$2 from "./actions/submitActivation.ts";
import * as $$$$$$$$$3 from "./actions/submitToConvex.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/ActivationForm.tsx";
import * as $$$$$$1 from "./sections/Benefits.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/ContactFormHybrid.tsx";
import * as $$$$$$4 from "./sections/Derivative.tsx";
import * as $$$$$$5 from "./sections/Faq.tsx";
import * as $$$$$$6 from "./sections/Footer.tsx";
import * as $$$$$$8 from "./sections/Header_default.tsx";
import * as $$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$18 from "./sections/hero-1.tsx";
import * as $$$$$$19 from "./sections/hero-2.tsx";
import * as $$$$$$9 from "./sections/Hero.tsx";
import * as $$$$$$20 from "./sections/hero2.tsx";
import * as $$$$$$10 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$11 from "./sections/Logos.tsx";
import * as $$$$$$12 from "./sections/Mission.tsx";
import * as $$$$$$13 from "./sections/NetworkRecoverySteps.tsx";
import * as $$$$$$14 from "./sections/Services.tsx";
import * as $$$$$$15 from "./sections/Supporters.tsx";
import * as $$$$$$16 from "./sections/Theme/Theme.tsx";
import * as $$$$$$17 from "./sections/UnicornStudioEffect.tsx";

const manifest = {
  "sections": {
    "site/sections/ActivationForm.tsx": $$$$$$0,
    "site/sections/Benefits.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/ContactFormHybrid.tsx": $$$$$$3,
    "site/sections/Derivative.tsx": $$$$$$4,
    "site/sections/Faq.tsx": $$$$$$5,
    "site/sections/Footer.tsx": $$$$$$6,
    "site/sections/Header_default.tsx": $$$$$$8,
    "site/sections/Header.tsx": $$$$$$7,
    "site/sections/hero-1.tsx": $$$$$$18,
    "site/sections/hero-2.tsx": $$$$$$19,
    "site/sections/Hero.tsx": $$$$$$9,
    "site/sections/hero2.tsx": $$$$$$20,
    "site/sections/ImageWithParagraph.tsx": $$$$$$10,
    "site/sections/Logos.tsx": $$$$$$11,
    "site/sections/Mission.tsx": $$$$$$12,
    "site/sections/NetworkRecoverySteps.tsx": $$$$$$13,
    "site/sections/Services.tsx": $$$$$$14,
    "site/sections/Supporters.tsx": $$$$$$15,
    "site/sections/Theme/Theme.tsx": $$$$$$16,
    "site/sections/UnicornStudioEffect.tsx": $$$$$$17,
  },
  "actions": {
    "site/actions/contactFormConvex.ts": $$$$$$$$$0,
    "site/actions/contactFormConvexFixed.ts": $$$$$$$$$1,
    "site/actions/submitActivation.ts": $$$$$$$$$2,
    "site/actions/submitToConvex.ts": $$$$$$$$$3,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
